### ISSUE TITLE
`NoContent` is an elm type, but it doesn't exist.

### ISSUE THREAD

**Issue by mebassett** [folq/servant-to-elm#2]
https://github.com/folq/servant-to-elm/blob/e5f6f42cd2bb3d739f75acbe22490b5e556999a4/src/Servant/To/Elm.hs#L613

Maybe `Never` would be better here?  
To get around this, I created an Elm file that looks like 
```elm
module NoContent exposing (..)
type NoContent = NoContent
```

though its more than likely that I'm just being daff.

**Comment by ollef** [comment]
Hey!

We do the same as you do currently, but it'd be nice if we could come up with a better solution for `NoContent`. If not, the current behaviour needs to be documented at the very least.

The endpoint generator has some special-casing for `NoContent` that checks that the body is actually empty, but that's probably not terribly important. Perhaps a solution would be to use `()`? (`Never` wouldn't work because you can't create a value of that type.)

**Comment by ollef** [comment]
I think I managed to find a pretty nice fix using `()`. If you upgrade to version 0.4.0.0 the `NoContent` module is no longer necessary.

Let me know if the fix works out for you. :)

**Comment by mebassett** [comment]
holy response times, batman!  
that was fast.  Thanks!  Unfortunately my compiler complains about missing instances:
```
    • No instance for (Language.Haskell.To.Elm.HasElmDecoder
                         aeson-1.4.6.0:Data.Aeson.Types.Internal.Value
                         servant-0.16.2:Servant.API.ContentTypes.NoContent)
        arising from a use of ‘elmEndpoints’

```

**Comment by ollef** [comment]
No problem!

You now need to use the `...NoContent` verb variants in your Servant API, such as [`GetNoContent`](http://hackage.haskell.org/package/servant-0.16.2/docs/Servant-API-Verbs.html#t:GetNoContent), for it to work.

If you don't want to do that, you can probably add orphan instances for `HasElmType NoContent` and `HasElmDecoder Aeson.Value NoContent`, perhaps mapping them to Elm's unit type.
