### ISSUE TITLE
Parameterize over URL base

### ISSUE THREAD

**Issue by seagreen** [folq/servant-to-elm#4]
Having a hardcoded `Config` module works well if the frontend and backend are always on the same domain. However, if they're on different domains the user will likely want some way to parameterize over the URL base.

The simplest way to do this is to add a URL base `String` parameter to each generated function, eg: https://github.com/seagreen/servant-to-elm/commit/3b5d51f804faa9de6e0242b088154e4edd4937ae

What are your thoughts on the situation? Let me know if you'd like a PR made from that commit.

**Comment by ollef** [comment]
This sounds like a good idea if we can make the parameter optional, e.g. by taking an `URLBase` ADT that allows choosing between the current behaviour (a constant `Expression`) and the parameter.

The way we solve this problem is to symlink aifferent `Config` modules depending on the environment we're building for, which saves us from having to pass around stuff like the URL base in the frontend.

**Comment by seagreen** [comment]
:+1: on making it optional. I'll make a PR if I get around to it, but no promises.

**Comment by ollef** [comment]
`elmEndpointRequestInfo` can now be used to achieve this. :tada:
